BEGIN;

-- Table Suggestion
CREATE TABLE IF NOT EXISTS "Suggestion" (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"    INTEGER NOT NULL,
  title       VARCHAR(150) NOT NULL,
  content     TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index
CREATE INDEX IF NOT EXISTS "Suggestion_userId_idx" ON "Suggestion" ("userId");
CREATE INDEX IF NOT EXISTS "Suggestion_createdAt_idx" ON "Suggestion" ("createdAt");

-- FK (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'Suggestion_userId_fkey'
      AND table_name = 'Suggestion'
  ) THEN
    ALTER TABLE "Suggestion"
      ADD CONSTRAINT "Suggestion_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE;
  END IF;
END $$;

COMMIT;
